Store.Web/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using wise_nut;
using System.Linq;
using wise_nut.Web.App;
using System.Text;
using wise_nut.Contractors;
using Store.Web.Contractors;
using System.Net;
using System;

namespace Store.Web.Controllers
{
	public class OrderController : Controller
	{
		private readonly OrderService orderService;
		private readonly IEnumerable<IDeliveryService> deliveryServices;
		private readonly IEnumerable<IPaymentService> paymentServices;
		private readonly IEnumerable<IWebContractorService> webContractorServices;
		public OrderController(OrderService orderService,
							   IEnumerable<IDeliveryService> deliveryServices,
							   IEnumerable<IPaymentService> paymentServices,
							   IEnumerable<IWebContractorService> webContractorServices)
		{
			this.orderService = orderService;
			this.deliveryServices = deliveryServices;
			this.paymentServices = paymentServices;
			this.webContractorServices = webContractorServices;
		}

		[HttpGet]
		public IActionResult Index()
		{
			if (orderService.TryGetModel(out OrderModel model))
				return View(model);
			return View("Empty");
		}

		[HttpPost]
		public IActionResult AddItem(int productId, int count = 1)
		{
			orderService.AddProduct(productId, count);

			return RedirectToAction("Index", "Product", new { id = productId });
		}

		[HttpPost]
		public IActionResult UpdateItem(int productId, int count)
		{
			var model = orderService.UpdateProduct(productId, count);

			return View("Index", model);
		}

		[HttpPost]
		public IActionResult RemoveItem(int productId)
		{
			var model = orderService.RemoveProduct(productId);

			return View("Index", model);
		}

		[HttpPost]
		public IActionResult SendConfirmation(string cellPhone)
		{
			var model = orderService.SendConfirmation(cellPhone);
			return View("Confirmation", model);
		}

		[HttpPost]
		public IActionResult ConfirmCellPhone(string cellPhone, int confirmationCode)
		{
			var model = orderService.ConfirmCellPhone(cellPhone, confirmationCode);

			if (model.Errors.Count > 0)
				return View("Confirmation", model);
			var deliveryMethods = deliveryServices.ToDictionary(service => service.Name,
																service => service.Title);

			return View("DeliveryMethod", deliveryMethods);
		}

		[HttpPost]
		public IActionResult StartDelivery(string serviceName)
		{
			var deliveryService = deliveryServices.Single(service => service.Name == serviceName);
			var order = orderService.GetOrder();
			var form = deliveryService.FirstForm(order);

			var webContractorService = webContractorServices.SingleOrDefault(service => service.Name == serviceName);
			if (webContractorService == null)
				return View("DeliveryStep", form);

			var returnUri = GetReturnUri(nameof(NextDelivery));
			var redirectUri = webContractorService.StartSession(form.Parameters, returnUri);

			return Redirect(redirectUri.ToString());
		}

		private Uri GetReturnUri(string action)
		{
			var builder = new UriBuilder(Request.Scheme, Request.Host.Host)
			{
				Path = Url.Action(action),
				Query = null,
			};

			if (Request.Host.Port != null)
				builder.Port = Request.Host.Port.Value;

			return builder.Uri;
		}
		[HttpPost]
		public IActionResult NextDelivery(string serviceName, int step, Dictionary<string, string> values)
		{
			var deliveryService = deliveryServices.Single(service => service.Name == serviceName);

			var form = deliveryService.NextForm(step, values);
			if (!form.IsFinal)
				return View("DeliveryStep", form);

			var delivery = deliveryService.GetDelivery(form);
			orderService.SetDelivery(delivery);

			var paymentMethods = paymentServices.ToDictionary(service => service.Name,
															  service => service.Title);

			return View("PaymentMethod", paymentMethods);
		}

		[HttpPost]
		public IActionResult StartPayment(string serviceName)
		{
			var paymentService = paymentServices.Single(service => service.Name == serviceName);
			var order = orderService.GetOrder();
			var form = paymentService.FirstForm(order);

			var webContractorService = webContractorServices.SingleOrDefault(service => service.Name == serviceName);
			if (webContractorService == null)
				return View("PaymentStep", form);

			var returnUri = GetReturnUri(nameof(NextPayment));
			var redirectUri = webContractorService.StartSession(form.Parameters, returnUri);

			return Redirect(redirectUri.ToString());
		}

		[HttpPost]
		public IActionResult NextPayment(string serviceName, int step, Dictionary<string, string> values)
		{
			var paymentService = paymentServices.Single(service => service.Name == serviceName);

			var form = paymentService.NextForm(step, values);
			if (!form.IsFinal)
				return View("PaymentStep", form);

			var payment = paymentService.GetPayment(form);
			var model = orderService.SetPayment(payment);

			return View("Finish", model);
		}
	}
}

Store.Web/Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;
using wise_nut;
using wise_nut.Web.App;

namespace Store.Web.Controllers
{
    public class SearchController : Controller
    {
        private readonly ProductService productService;

        public SearchController(ProductService productService)
        {
            this.productService = productService;
        }
        public IActionResult Index(string query)
        {
            var products = productService.GetAllByQuery(query);
            return View("Index", products);
        }
    }
}

Store.Web/Views/Shared/NotFound.cshtml
@{
    ViewData["Title"] = "Страница не найдена";
}
<h1>Ой! А страница не найдена :(</h1>
<p>Но у нас есть еще много других товаров</p>

Store.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Мудрый Орех</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Store.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white">
            <a class="navbar-brand" asp-area=" asp-controller="Home" asp-action="Index">Мудрый Орех</a>
            <form class="form-inline my-2 my-lg-0" style="display: flex" action="@Url.Action("Index", "Search")" method="get">
                <input class="form-control mr-sm-2 " type="search" name="query" placeholder="Поиск товаров" />
                <button class="btn-outline-success my-2 my-sm-0" type="submit">Найти</button>
            </form>
            <span class="navbar-text" style="margin-left:auto">
                @{
                    if (Context.Session.TryGetCart(out Cart cart) && cart.TotalCount > 0)
                    {
                        <a href="@Url.Action("Index", "Order")">В корзине @cart.TotalCount товаров на сумму @cart.TotalPrice</a>
                    }
                    else
                    {
                        @:Корзина пуста
                    }
                }
            </span>
            <partial name="_LoginPartial" />
        </nav>
    </header>
    <div class="container">
        <main>
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>